    
site_name: yurita
theme: readthedocs
repo_url: https://github.com/paypal/yurita
edit_uri: blob/master/docs/
pages:
- Overview: 'index.md'
- About:
    - 'Contributing': 'CONTRIBUTING.md'
    - 'License': 'LICENSE.txt'
    - 'Presentations': 'presentations.md'
- Documentation:
    - 'Overview': 'overview.md'
    - 'High-level data flow': 'data-flow.md'
    - 'Architecture':
      - 'Anomaly Pipeline': 'pipeline.md'
      - 'Anomaly Workload': 'workload.md'
      - 'DataFrame API Extension': 'df-api-ext.md'
    - 'Models':
      - 'Categorical Model': 'categorical.md'
      - 'Numerical Model': 'numerical.md'
      - 'Density Based Clustering Model': 'density.md'
    - 'Aggregations and Data Structures': 'data-structures.md'
    - 'Example': 'example-code.md'
