site_name: yurita
theme: readthedocs
repo_url: https://github.com/paypal/yurita
edit_uri: blob/master/docs/
pages:
- Overview: 'index.md'
- About:
    - 'Contributing': 'CONTRIBUTING.md'
    - 'License': 'LICENSE.txt'
    - 'Presentations': 'presentations.md'
- Documentation:
    - 'High-level data flow': 'data-flow.md'
    - 'Architecture':
      - 'Anomaly Pipeline': 'pipeline.md'
      - 'Anomaly Workload': 'workload.md'
      - 'Models': 'model.md'
    - 'Example': 'example-code.md'
